NDefines.NDiplomacy.NUM_POSSIBLE_RIVALS = 5
NDefines.NDiplomacy.DESIRED_NUM_OF_ELECTORS = 8
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 15
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 50						-- Minimum Cost of enacting a new reform.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 33				-- Mandate cost of enacting a new reform for the Emperor of China.
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0		-- Stability cost of enacting a new reform for the Emperor of China
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 66			-- Minimum value of Mandate above which new reforms can be enacted.
NDefines.NDiplomacy.DEFENDER_OF_FAITH_COST = 1000 					-- _DDEF_DEFENDER_OF_FAITH_COST_
NDefines.NDiplomacy.DEFENDER_OF_FAITH_MONTHS = 36 					-- _DDEF_DEFENDER_OF_FAITH_MONTHS_ (Minimum months before it can be taken from another country with less prestige)
NDefines.NDiplomacy.EXCOMMUNICATE_ACTION_MONTHS = 24 				-- Excommunication "cooldown" (months)
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 25 					-- Crusade timeout (years)
NDefines.NDiplomacy.EMPEROR_VOTE_DAYS = 30	 						-- _DDEF_EMPEROR_VOTE_DAYS_; "Cooldown" until Electors can change their vote again.
NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 75.0			-- Cost for the emperor to revoke a reform
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 5							-- Additional years of truce based on % of warscore taken in war (100% warscore = full scaled truce years)
NDefines.NDiplomacy.WARNING_YEARS = 10								-- Years before warning expire
NDefines.NDiplomacy.HRE_VOTE_HERETIC = -10
NDefines.NDiplomacy.HRE_VOTE_OVERLORD = 100
NDefines.NDiplomacy.HRE_VOTE_VASSAL_ELECTOR = -100
NDefines.NDiplomacy.HRE_VOTE_TOO_SMALL = 0
NDefines.NDiplomacy.HRE_VOTE_NON_MEMBER = -100
NDefines.NDiplomacy.HRE_VOTE_ROYAL_MARRIAGE = 25
NDefines.NDiplomacy.HRE_VOTE_CORE_CLAIM = -100
NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.25
NDefines.NDiplomacy.AE_SAME_RELIGION_GROUP = 0.25
NDefines.NDiplomacy.AE_DIFFERENT_RELIGION = 0.25
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.25
NDefines.NDiplomacy.AE_DISTANCE_BASE = 0.75
NDefines.NDiplomacy.AE_PROVINCE_CAP = 25							-- Province development above this will not count for AE (also used for warscore cost cap)
NDefines.NDiplomacy.PO_RETURN_CORES_AE = 0.25 						-- (Per core only applied if returning cores to vassals of winner)
NDefines.NDiplomacy.PO_ANNEX_PRESTIGE = 0.25 	        			-- _DDEF_PO_ANNEX_PRESTIGE = 10 (No effect on loser :)
NDefines.NDiplomacy.PO_FORCE_OUT_COLONIZERS_PRESTIGE = 2
NDefines.NDiplomacy.PO_ENFORCE_REBEL_DEMANDS_PRESTIGE = 2
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 10 						-- _DDEF_PEACE_COST_GOLD_STEP_ Peace Cost for 1 loan size gold of giver
NDefines.NDiplomacy.PEACE_COST_GOLD_MAX = 10						-- Maximum loans of gold that can be demanded from giver in peace.
NDefines.NDiplomacy.PEACE_COST_FORCE_MIGRATION = 100.0
NDefines.NDiplomacy.PEACE_COST_FORCE_OUT_COLONIZERS = 100.0
NDefines.NDiplomacy.PEACE_COST_ENFORCE_REBEL_DEMANDS = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 80		-- Starting value for Mandate value of a new Chinese Emperor
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_NONTRIBUTARY_DEV = -0.15	-- Yearly change of Mandate for each hundred development of neighbouring states that are not the Emperor's tributaries
NDefines.NDiplomacy.AUTODIPLO_TARGET_COALITION_HOPELESS_LIMIT = -100
NDefines.NDiplomacy.AUTODIPLO_TARGET_ALLIES_HOPELESS_LIMIT = -75
NDefines.NDiplomacy.SAME_TRIBUTARY_OVERLORD_SUPPORT_INDEPENDENCE_CHANCE = -5
NDefines.NCountry.EXPLOIT_ADM_INCOME = 120							-- months of income
NDefines.NCountry.EXPLOIT_DIP_SAILORS = 12
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 12
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 360
NDefines.NCountry.CONSOLIDATE_DEVELOPMENT_COOLDOWN_DURATION = 10
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_BASE = 10				-- monthly..
NDefines.NCountry.GOLDEN_ERA_YEARS = 100
NDefines.NCountry.SPLENDOR_ABILITY_COST = 600
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.25		-- different continent
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.5			-- non accepted culture
NDefines.NCountry.ESTATE_CROWNLAND_FROM_DEV = 0.25					-- How much crownland you gain from developing a province.
NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 3						-- Capital must have at least this much development to be a free city
NDefines.NCountry.HRE_INCIDENT_ELECTOR_SUPPORT_IA = 2				-- How much worth an elector support is in an incident
NDefines.NCountry.HRE_INCIDENT_MEMBER_SUPPORT_IA = 0.5				-- How much worth an elector support is in an incident
NDefines.NCountry.HRE_INCIDENT_AI_EMPEROR_OPINION = 0.10			-- How much opinion with emperor is worth for AI to side with him
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_3 = 20				-- Prestige gained on upgrading to government rank 3
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 600				-- Need at least this much development to upgrade to government rank 2
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 1200			-- Need at least this much development to upgrade to government rank 3
NDefines.NCountry.ADDITIONAL_MIN_DEVELOPMENT_FOR_GOV_RANK_X = 250	-- ADDITIONAL development needed to upgrade to government rank above 3
NDefines.NCountry.PARLIAMENT_BACKING_PERCENTAGE = 33				-- average percent of seats backing an issue (0-100)
NDefines.NCountry.GREAT_PROJECT_MOVE_COST_PER_DAY = 1 				--how much to move a great project for one day
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.80				-- percentage of piety kept at new ruler.
NDefines.NCountry.ADVISOR_CUT_OFF_AGE = 60 						-- _CDEF_ADVISOR_CUT_OFF_AGE = 10
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10						-- Maximum advisor skill reachable through promotion
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 15			-- Minimum development required to promote the culture.
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 2		-- Stab hit on monarch death when a leader
NDefines.NCountry.MIN_REGENCY_LEGITIMACY = 80
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 6 						-- maximum tolerance towards heretics
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 6 						-- maximum tolerance towards heathens
NDefines.NCountry.PS_ADD_TRIBAL_LAND = 100
NDefines.NCountry.PS_FORCE_MARCH = 2
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 5
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE_UNREST_DURATION = 2.5
NDefines.NCountry.CLAIM_LOSE = 75									-- how many years until a claim is lost.
NDefines.NCountry.CORE_LOSE = 200 									-- how many years until a core is lost.
NDefines.NCountry.AGE_OF_ADULTHOOD = 13 							-- _CDEF_AGE_OF_ADULTHOOD_
NDefines.NCountry.MAX_EXTRA_PERSONALITIES = 3						-- Number of personalities that can be gained except the one you get when turning 15.
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 5					-- Number of years between new personalities after first one.
NDefines.NCountry.INITIAL_REGULAR_COLONY = 25
NDefines.NCountry.MONTHS_TO_CORE = 24								-- How many months it will take to core a province.
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 12					-- How many months it will take to change culture in a province per development.
NDefines.NCountry.MAX_CROWN_COLONIES = 4							-- How many province a country can hold in a colonial region before creating a colonial nation
NDefines.NCountry.RAZE_UNREST_DURATION = 10						-- Years of unrest. Also used for duration of neg. opinion modifier for previous owner.
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2.0  	-- Innovativeness bonus to first country (or countries) to reach a certain tech level.
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.0			-- Innovativeness bonus to first country (or countries) to pick an idea.
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0.005 		-- Bonus for being ahead of time in tech
NDefines.NCountry.INNOVATIVENESS_DAYS_AFTER_FIRST_PICK_VIABLE = 90 -- How many days you cna still get innov
NDefines.NCountry.MIGRATORY_TRIBE_DEVASTATION_BURN = 5.0			-- How much devastation is burnt per month multiplied with development.
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_PROGRESS = 0.05 		-- How much progress on development for each monthly tick
NDefines.NCountry.MIGRATORY_TRIBE_DEVELOPMENT_OTHER_BONUS = 0.1	-- Bonus progress gained on development from burning someone else province.
NDefines.NMilitary.WARDEC_COBELLI_FOR_WARNINGS = 1
NDefines.NReligion.CONSECRATE_PATRIARCH_THRESHOLD = 15 			--in development
NDefines.NReligion.ORTHODOX_ICON_DURATION_MONTHS = 120
NDefines.NReligion.ORTHODOX_ICON_AUTHORITY_COST = 0.05
NDefines.NReligion.AUTHORITY_FROM_DEVELOPMENT = 0.2
NDefines.NReligion.MAYA_COLLAPSE_PROVINCES = 20					-- Maya collapses to this size on reform
NDefines.NReligion.MAYA_COLLAPSE_PROVINCES_PER_REFORM = 4			-- Maya keeps this many extra provinces per reform
NDefines.NReligion.RELIGIOUS_LEAGUE_COOLDOWN = 2					-- Minimum years between joining/leaving religious league
NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 3				-- The number of spawned centers of reformation wont exceed this number
NDefines.NReligion.MAX_RELIGIOUS_CENTER_SPREAD_DISTANCE = 100.0	-- When spreading the religion to other provinces the distance wont exceed this number
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 9125					-- Amount of days in which you cannot convert the province back.
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.006					-- Increase of reform descire for each year.
NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 3					-- Base is 20
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -1.5 -- Base game is -3%
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.06 			-- Base game is 3%
NDefines.NReligion.CONVERSION_COOLDOWN = 300						-- months before you can convert again.
NDefines.NGovernment.TRIBAL_ALLEGIANCE_HUMILIATE = 100
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 33
NDefines.NGovernment.PRESTIGE_TO_TRIBAL_ALLEGIANCE_FACTOR = 5